-- +migrate Up

CREATE TABLE `type` (
    type_id VARCHAR(26) NOT NULL PRIMARY KEY,
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    deleted_at DATETIME DEFAULT NULL,

    name VARCHAR(255) NOT NULL UNIQUE
);

-- +migrate Down

DROP TABLE IF EXISTS `type`;