#!/usr/bin/env bash

function main() {
	local rootDir="$(dirname "${0}")"

	mkdir -p "${rootDir}/.bin"
	pushd "$_" &>/dev/null
	export GOBIN="${PWD}"
	popd &>/dev/null

	pushd "${rootDir}" &>/dev/null
	go install github.com/codemodus/withdraw@v0.1.0
	go install github.com/go-bindata/go-bindata/go-bindata@v3.1.1
	go install google.golang.org/protobuf/cmd/protoc-gen-go@v1.25.0
	go install google.golang.org/grpc/cmd/protoc-gen-go-grpc@v1.1.0
	go install github.com/grpc-ecosystem/grpc-gateway/v2/protoc-gen-grpc-gateway@v2.2.0
	go install github.com/grpc-ecosystem/grpc-gateway/v2/protoc-gen-openapiv2@v2.2.0
	popd &>/dev/null

	unset GOBIN
}

main
