#!/usr/bin/env bash
set -e

ostype="$([[ "${OSTYPE}" == "darwin"* ]] && echo "darwin" || echo "linux")"

if [[ ! $(hash mysql 2>/dev/null) ]]; then
	if [[ "${ostype}" == "linux" ]]; then
		sudo apt update
		sudo apt install software-properties-common

		pkey="0xF1656F24C74CD1D8"
		if grep -qi "Microsoft\|WSL" /proc/version; then
			keysrch="http://keyserver.ubuntu.com/pks/lookup?op=get&search=${pkey}"
			curl -sL "${keysrch}" | sudo apt-key add
		else
			keysrv="hkp://keyserver.ubuntu.com:80"
			sudo apt-key adv --recv-keys --keyserver "${keysrv}" "${pkey}"
		fi
		repourl=http://sfo1.mirrors.digitalocean.com/mariadb/repo/10.3/ubuntu 
		sudo add-apt-repository "deb [arch=amd64] ${repourl} $(lsb_release -cs) main"
		sudo apt update
		sudo apt install mariadb-server
	fi
	if [[ "${ostype}" == "darwin" ]]; then
		brew update
		brew install mariadb
	fi

	sudo cat << EOF > /etc/mysql/mariadb.conf.d/60-encoding.cnf
[mysqld]
character-set-server = utf8mb4
collation-server     = utf8mb4_unicode_ci
character_set_server = utf8mb4
collation_server     = utf8mb4_unicode_ci
EOF

	if [[ "${ostype}" == "linux" ]]; then
		sudo systemctl restart mariadb
	fi
	if [[ "${ostype}" == "darwin" ]]; then
		mysql.server start
		brew services start mariadb
	fi
fi

adddb=""
rootpass=""
echo "add database? [y/N]"
read adddb
[[ ! ${adddb} =~ y|Y ]] && exit 0
echo "mysql root pass:"
read -s rootpass

dbname=""
dbuser=""
dbpass=""
echo "database name:"
read dbname
echo "database user:"
read dbuser
echo "database pass:"
read -s dbpass

mysql -uroot -p"${rootpass}" << EOF
CREATE DATABASE ${dbname} DEFAULT CHARACTER SET utf8mb4 DEFAULT COLLATE utf8mb4_unicode_ci;
GRANT ALL PRIVILEGES ON ${dbname}.* TO ${dbuser}@'%' IDENTIFIED BY '${dbpass}';
EOF
