#!/usr/bin/env bash

install-protoc() {
  local dest="${1}"
  local version="${2}"
  local ostype="$([[ "${OSTYPE}" == darwin* ]] && echo osx || echo linux)"
  local arch="$(uname -m)"
  local pfmt="https://github.com/protocolbuffers/protobuf/releases/download/v%s/protoc-%s-%s-%s.zip"
  local path="$(printf "${pfmt}" "${version}" "${version}" "${ostype}" "${arch}")"
  local tmpDir="$(mktemp -d)"
  local zipFile="${tmpDir}/protoc.zip"
  wget -O "${zipFile}" "${path}"
  unzip -j ${zipFile} bin/protoc
}

main() {
  local rootDir="$(cd "$(dirname "${0}")" && echo "${PWD}")"
  local binDir="${rootDir}/.bin"

  mkdir -p "${binDir}"
  pushd "${binDir}" &> /dev/null && rm "${binDir}/"*

  export GOBIN="${PWD}"
  go install github.com/codemodus/withdraw@v0.1.0
  go install github.com/go-bindata/go-bindata/go-bindata@v3.1.1
  go install google.golang.org/protobuf/cmd/protoc-gen-go@v1.25.0
  go install google.golang.org/grpc/cmd/protoc-gen-go-grpc@v1.1.0
  go install github.com/grpc-ecosystem/grpc-gateway/v2/protoc-gen-grpc-gateway@v2.2.0
  go install github.com/grpc-ecosystem/grpc-gateway/v2/protoc-gen-openapiv2@v2.2.0

  install-protoc "${PWD}" 3.17.0

  popd &> /dev/null
}

main
