#!/usr/bin/env bash

function main() {
	local proj="github.com/OpenEugene/openboard/back"
	local pkgs=(\
		"internal/pb" \
		"internal/httpsrv" \
	)

	for pkg in "${pkgs[@]}"; do
		go generate "${proj}/${pkg}"
	done
}

main
