-- +migrate Up

CREATE TABLE post (
    post_id VARCHAR(26) NOT NULL PRIMARY KEY,
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    deleted_at DATETIME DEFAULT NULL,

    type_id VARCHAR(26) NOT NULL,
    slug VARCHAR(255) NULL,
    title VARCHAR(255) NULL,
    body VARCHAR(255) NULL
);

-- +migrate Down

DROP TABLE IF EXISTS post;