// Code generated by protoc-gen-go. DO NOT EDIT.
// source: auth.proto

// openboard
//
// auth semantics:
//
//  Add{T}(s)    (Add{T}(s)Req)    returns {T}(s)Resp // POST
//  Ovr{T}(s)    (Ovr{T}(s)Req)    returns {T}(s)Resp // PUT
//  Mod{T}(s)    (Mod{T}(s)Req)    returns {T}(s)Resp // PATCH
//  Get{T}       (Get{T}Req)       returns {T}Resp    // GET
//  Fnd{T}s      (Fnd{T}sReq)      returns {T}sResp   // GET
//  Rmv{T}(s)    (Rmv{T}(s)Req)    returns EmptyResp  // DELETE
//  Unr{T}       (Unr{T}Req)       returns {T}Resp    // PATCH

package pb

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type AuthResp struct {
	Token                string   `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AuthResp) Reset()         { *m = AuthResp{} }
func (m *AuthResp) String() string { return proto.CompactTextString(m) }
func (*AuthResp) ProtoMessage()    {}
func (*AuthResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_8bbd6f3875b0e874, []int{0}
}

func (m *AuthResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AuthResp.Unmarshal(m, b)
}
func (m *AuthResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AuthResp.Marshal(b, m, deterministic)
}
func (m *AuthResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AuthResp.Merge(m, src)
}
func (m *AuthResp) XXX_Size() int {
	return xxx_messageInfo_AuthResp.Size(m)
}
func (m *AuthResp) XXX_DiscardUnknown() {
	xxx_messageInfo_AuthResp.DiscardUnknown(m)
}

var xxx_messageInfo_AuthResp proto.InternalMessageInfo

func (m *AuthResp) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

type AddAuthReq struct {
	Username             string   `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Password             string   `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AddAuthReq) Reset()         { *m = AddAuthReq{} }
func (m *AddAuthReq) String() string { return proto.CompactTextString(m) }
func (*AddAuthReq) ProtoMessage()    {}
func (*AddAuthReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_8bbd6f3875b0e874, []int{1}
}

func (m *AddAuthReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddAuthReq.Unmarshal(m, b)
}
func (m *AddAuthReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddAuthReq.Marshal(b, m, deterministic)
}
func (m *AddAuthReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddAuthReq.Merge(m, src)
}
func (m *AddAuthReq) XXX_Size() int {
	return xxx_messageInfo_AddAuthReq.Size(m)
}
func (m *AddAuthReq) XXX_DiscardUnknown() {
	xxx_messageInfo_AddAuthReq.DiscardUnknown(m)
}

var xxx_messageInfo_AddAuthReq proto.InternalMessageInfo

func (m *AddAuthReq) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *AddAuthReq) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

type RmvAuthResp struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RmvAuthResp) Reset()         { *m = RmvAuthResp{} }
func (m *RmvAuthResp) String() string { return proto.CompactTextString(m) }
func (*RmvAuthResp) ProtoMessage()    {}
func (*RmvAuthResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_8bbd6f3875b0e874, []int{2}
}

func (m *RmvAuthResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RmvAuthResp.Unmarshal(m, b)
}
func (m *RmvAuthResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RmvAuthResp.Marshal(b, m, deterministic)
}
func (m *RmvAuthResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RmvAuthResp.Merge(m, src)
}
func (m *RmvAuthResp) XXX_Size() int {
	return xxx_messageInfo_RmvAuthResp.Size(m)
}
func (m *RmvAuthResp) XXX_DiscardUnknown() {
	xxx_messageInfo_RmvAuthResp.DiscardUnknown(m)
}

var xxx_messageInfo_RmvAuthResp proto.InternalMessageInfo

type RmvAuthReq struct {
	Token                string   `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RmvAuthReq) Reset()         { *m = RmvAuthReq{} }
func (m *RmvAuthReq) String() string { return proto.CompactTextString(m) }
func (*RmvAuthReq) ProtoMessage()    {}
func (*RmvAuthReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_8bbd6f3875b0e874, []int{3}
}

func (m *RmvAuthReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RmvAuthReq.Unmarshal(m, b)
}
func (m *RmvAuthReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RmvAuthReq.Marshal(b, m, deterministic)
}
func (m *RmvAuthReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RmvAuthReq.Merge(m, src)
}
func (m *RmvAuthReq) XXX_Size() int {
	return xxx_messageInfo_RmvAuthReq.Size(m)
}
func (m *RmvAuthReq) XXX_DiscardUnknown() {
	xxx_messageInfo_RmvAuthReq.DiscardUnknown(m)
}

var xxx_messageInfo_RmvAuthReq proto.InternalMessageInfo

func (m *RmvAuthReq) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

type AddVoucherResp struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AddVoucherResp) Reset()         { *m = AddVoucherResp{} }
func (m *AddVoucherResp) String() string { return proto.CompactTextString(m) }
func (*AddVoucherResp) ProtoMessage()    {}
func (*AddVoucherResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_8bbd6f3875b0e874, []int{4}
}

func (m *AddVoucherResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddVoucherResp.Unmarshal(m, b)
}
func (m *AddVoucherResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddVoucherResp.Marshal(b, m, deterministic)
}
func (m *AddVoucherResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddVoucherResp.Merge(m, src)
}
func (m *AddVoucherResp) XXX_Size() int {
	return xxx_messageInfo_AddVoucherResp.Size(m)
}
func (m *AddVoucherResp) XXX_DiscardUnknown() {
	xxx_messageInfo_AddVoucherResp.DiscardUnknown(m)
}

var xxx_messageInfo_AddVoucherResp proto.InternalMessageInfo

type AddVoucherReq struct {
	Notify               bool     `protobuf:"varint,1,opt,name=notify,proto3" json:"notify,omitempty"`
	Email                string   `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	Password             bool     `protobuf:"varint,3,opt,name=password,proto3" json:"password,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AddVoucherReq) Reset()         { *m = AddVoucherReq{} }
func (m *AddVoucherReq) String() string { return proto.CompactTextString(m) }
func (*AddVoucherReq) ProtoMessage()    {}
func (*AddVoucherReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_8bbd6f3875b0e874, []int{5}
}

func (m *AddVoucherReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddVoucherReq.Unmarshal(m, b)
}
func (m *AddVoucherReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddVoucherReq.Marshal(b, m, deterministic)
}
func (m *AddVoucherReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddVoucherReq.Merge(m, src)
}
func (m *AddVoucherReq) XXX_Size() int {
	return xxx_messageInfo_AddVoucherReq.Size(m)
}
func (m *AddVoucherReq) XXX_DiscardUnknown() {
	xxx_messageInfo_AddVoucherReq.DiscardUnknown(m)
}

var xxx_messageInfo_AddVoucherReq proto.InternalMessageInfo

func (m *AddVoucherReq) GetNotify() bool {
	if m != nil {
		return m.Notify
	}
	return false
}

func (m *AddVoucherReq) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *AddVoucherReq) GetPassword() bool {
	if m != nil {
		return m.Password
	}
	return false
}

func init() {
	proto.RegisterType((*AuthResp)(nil), "pb.AuthResp")
	proto.RegisterType((*AddAuthReq)(nil), "pb.AddAuthReq")
	proto.RegisterType((*RmvAuthResp)(nil), "pb.RmvAuthResp")
	proto.RegisterType((*RmvAuthReq)(nil), "pb.RmvAuthReq")
	proto.RegisterType((*AddVoucherResp)(nil), "pb.AddVoucherResp")
	proto.RegisterType((*AddVoucherReq)(nil), "pb.AddVoucherReq")
}

func init() { proto.RegisterFile("auth.proto", fileDescriptor_8bbd6f3875b0e874) }

var fileDescriptor_8bbd6f3875b0e874 = []byte{
	// 316 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x91, 0xbf, 0x4e, 0xeb, 0x30,
	0x14, 0x87, 0x95, 0xde, 0xdb, 0x36, 0x1c, 0x48, 0x5b, 0xcc, 0x1f, 0x55, 0x11, 0x43, 0xe5, 0x09,
	0x75, 0x48, 0x24, 0x98, 0xe8, 0x16, 0x89, 0x81, 0x39, 0x03, 0x12, 0xa3, 0x43, 0x4c, 0x13, 0xd1,
	0xd8, 0x4e, 0xec, 0x14, 0x21, 0xc4, 0xc2, 0x2b, 0xf0, 0x5e, 0x2c, 0xbc, 0x02, 0x0f, 0x82, 0x62,
	0x3b, 0x09, 0x45, 0x62, 0xfc, 0x8e, 0xcf, 0xcf, 0x3e, 0xdf, 0x31, 0x00, 0xa9, 0x55, 0x16, 0x88,
	0x8a, 0x2b, 0x8e, 0x06, 0x22, 0xf1, 0xcf, 0xd6, 0x9c, 0xaf, 0x37, 0x34, 0x24, 0x22, 0x0f, 0x09,
	0x63, 0x5c, 0x11, 0x95, 0x73, 0x26, 0x4d, 0x07, 0x5e, 0x80, 0x1b, 0xd5, 0x2a, 0x8b, 0xa9, 0x14,
	0xe8, 0x18, 0x86, 0x8a, 0x3f, 0x52, 0x36, 0x77, 0x16, 0xce, 0xf9, 0x5e, 0x6c, 0x00, 0x5f, 0x03,
	0x44, 0x69, 0x6a, 0x9a, 0x4a, 0xe4, 0x83, 0x5b, 0x4b, 0x5a, 0x31, 0x52, 0x50, 0xdb, 0xd6, 0x71,
	0x73, 0x26, 0x88, 0x94, 0x4f, 0xbc, 0x4a, 0xe7, 0x03, 0x73, 0xd6, 0x32, 0xf6, 0x60, 0x3f, 0x2e,
	0xb6, 0xed, 0x53, 0x18, 0x03, 0x74, 0x58, 0xfe, 0xf1, 0xf0, 0x0c, 0x26, 0x51, 0x9a, 0xde, 0xf2,
	0xfa, 0x3e, 0xa3, 0x95, 0x4e, 0xdd, 0x81, 0xf7, 0xb3, 0x52, 0xa2, 0x53, 0x18, 0x31, 0xae, 0xf2,
	0x87, 0x67, 0x9d, 0x74, 0x63, 0x4b, 0xcd, 0x85, 0xb4, 0x20, 0xf9, 0xc6, 0x8e, 0x61, 0x60, 0x67,
	0xbe, 0x7f, 0xba, 0xbf, 0xe3, 0x8b, 0x0f, 0x07, 0xfe, 0x37, 0xe3, 0xa0, 0x2b, 0x18, 0x5b, 0x5d,
	0x34, 0x09, 0x44, 0x12, 0xf4, 0xee, 0xfe, 0x81, 0xe6, 0x56, 0x61, 0xf6, 0xf6, 0xf9, 0xf5, 0x3e,
	0x00, 0x3c, 0x0c, 0x9b, 0x85, 0xaf, 0x9c, 0x25, 0x8a, 0x60, 0x6c, 0xa5, 0x4c, 0xb4, 0x37, 0xf4,
	0xa7, 0x3b, 0x2c, 0x05, 0x3e, 0xd1, 0xe9, 0xe9, 0xd2, 0xd3, 0xe9, 0xf0, 0x45, 0x2b, 0xbf, 0xa2,
	0x1b, 0xbd, 0x6c, 0x6b, 0x88, 0x0e, 0xed, 0x00, 0xbd, 0xb1, 0x8f, 0x7e, 0x97, 0xa4, 0xc0, 0x47,
	0xfa, 0x2e, 0x0f, 0xbb, 0xe1, 0xd6, 0x54, 0x57, 0xce, 0x32, 0x19, 0xe9, 0xff, 0xbd, 0xfc, 0x0e,
	0x00, 0x00, 0xff, 0xff, 0x27, 0x22, 0xf2, 0xd7, 0x0f, 0x02, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// AuthClient is the client API for Auth service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type AuthClient interface {
	AddAuth(ctx context.Context, in *AddAuthReq, opts ...grpc.CallOption) (*AuthResp, error)
	RmvAuth(ctx context.Context, in *RmvAuthReq, opts ...grpc.CallOption) (*RmvAuthResp, error)
	AddVoucher(ctx context.Context, in *AddVoucherReq, opts ...grpc.CallOption) (*AddVoucherResp, error)
}

type authClient struct {
	cc *grpc.ClientConn
}

func NewAuthClient(cc *grpc.ClientConn) AuthClient {
	return &authClient{cc}
}

func (c *authClient) AddAuth(ctx context.Context, in *AddAuthReq, opts ...grpc.CallOption) (*AuthResp, error) {
	out := new(AuthResp)
	err := c.cc.Invoke(ctx, "/pb.Auth/AddAuth", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authClient) RmvAuth(ctx context.Context, in *RmvAuthReq, opts ...grpc.CallOption) (*RmvAuthResp, error) {
	out := new(RmvAuthResp)
	err := c.cc.Invoke(ctx, "/pb.Auth/RmvAuth", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authClient) AddVoucher(ctx context.Context, in *AddVoucherReq, opts ...grpc.CallOption) (*AddVoucherResp, error) {
	out := new(AddVoucherResp)
	err := c.cc.Invoke(ctx, "/pb.Auth/AddVoucher", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AuthServer is the server API for Auth service.
type AuthServer interface {
	AddAuth(context.Context, *AddAuthReq) (*AuthResp, error)
	RmvAuth(context.Context, *RmvAuthReq) (*RmvAuthResp, error)
	AddVoucher(context.Context, *AddVoucherReq) (*AddVoucherResp, error)
}

func RegisterAuthServer(s *grpc.Server, srv AuthServer) {
	s.RegisterService(&_Auth_serviceDesc, srv)
}

func _Auth_AddAuth_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddAuthReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthServer).AddAuth(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.Auth/AddAuth",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthServer).AddAuth(ctx, req.(*AddAuthReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Auth_RmvAuth_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RmvAuthReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthServer).RmvAuth(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.Auth/RmvAuth",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthServer).RmvAuth(ctx, req.(*RmvAuthReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Auth_AddVoucher_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddVoucherReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthServer).AddVoucher(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.Auth/AddVoucher",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthServer).AddVoucher(ctx, req.(*AddVoucherReq))
	}
	return interceptor(ctx, in, info, handler)
}

var _Auth_serviceDesc = grpc.ServiceDesc{
	ServiceName: "pb.Auth",
	HandlerType: (*AuthServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "AddAuth",
			Handler:    _Auth_AddAuth_Handler,
		},
		{
			MethodName: "RmvAuth",
			Handler:    _Auth_RmvAuth_Handler,
		},
		{
			MethodName: "AddVoucher",
			Handler:    _Auth_AddVoucher_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "auth.proto",
}
