// Code generated by protoc-gen-go. DO NOT EDIT.
// source: post.proto

// openboard
//
// user semantics:
//
//  Add{T}(s)    (Add{T}(s)Req)    returns {T}(s)Resp // POST
//  Ovr{T}(s)    (Ovr{T}(s)Req)    returns {T}(s)Resp // PUT
//  Mod{T}(s)    (Mod{T}(s)Req)    returns {T}(s)Resp // PATCH
//  Get{T}       (Get{T}Req)       returns {T}Resp    // GET
//  Fnd{T}s      (Fnd{T}sReq)      returns {T}sResp   // GET
//  Rmv{T}(s)    (Rmv{T}(s)Req)    returns EmptyResp  // DELETE
//  Unr{T}       (Unr{T}Req)       returns {T}Resp    // PATCH

package pb

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type CommentResp struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CommentResp) Reset()         { *m = CommentResp{} }
func (m *CommentResp) String() string { return proto.CompactTextString(m) }
func (*CommentResp) ProtoMessage()    {}
func (*CommentResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_e114ad14deab1dd1, []int{0}
}

func (m *CommentResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CommentResp.Unmarshal(m, b)
}
func (m *CommentResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CommentResp.Marshal(b, m, deterministic)
}
func (m *CommentResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CommentResp.Merge(m, src)
}
func (m *CommentResp) XXX_Size() int {
	return xxx_messageInfo_CommentResp.Size(m)
}
func (m *CommentResp) XXX_DiscardUnknown() {
	xxx_messageInfo_CommentResp.DiscardUnknown(m)
}

var xxx_messageInfo_CommentResp proto.InternalMessageInfo

type AddCommentResp struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AddCommentResp) Reset()         { *m = AddCommentResp{} }
func (m *AddCommentResp) String() string { return proto.CompactTextString(m) }
func (*AddCommentResp) ProtoMessage()    {}
func (*AddCommentResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_e114ad14deab1dd1, []int{1}
}

func (m *AddCommentResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddCommentResp.Unmarshal(m, b)
}
func (m *AddCommentResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddCommentResp.Marshal(b, m, deterministic)
}
func (m *AddCommentResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddCommentResp.Merge(m, src)
}
func (m *AddCommentResp) XXX_Size() int {
	return xxx_messageInfo_AddCommentResp.Size(m)
}
func (m *AddCommentResp) XXX_DiscardUnknown() {
	xxx_messageInfo_AddCommentResp.DiscardUnknown(m)
}

var xxx_messageInfo_AddCommentResp proto.InternalMessageInfo

type TypeResp struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TypeResp) Reset()         { *m = TypeResp{} }
func (m *TypeResp) String() string { return proto.CompactTextString(m) }
func (*TypeResp) ProtoMessage()    {}
func (*TypeResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_e114ad14deab1dd1, []int{2}
}

func (m *TypeResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TypeResp.Unmarshal(m, b)
}
func (m *TypeResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TypeResp.Marshal(b, m, deterministic)
}
func (m *TypeResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TypeResp.Merge(m, src)
}
func (m *TypeResp) XXX_Size() int {
	return xxx_messageInfo_TypeResp.Size(m)
}
func (m *TypeResp) XXX_DiscardUnknown() {
	xxx_messageInfo_TypeResp.DiscardUnknown(m)
}

var xxx_messageInfo_TypeResp proto.InternalMessageInfo

func (m *TypeResp) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *TypeResp) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type AddTypeReq struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AddTypeReq) Reset()         { *m = AddTypeReq{} }
func (m *AddTypeReq) String() string { return proto.CompactTextString(m) }
func (*AddTypeReq) ProtoMessage()    {}
func (*AddTypeReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_e114ad14deab1dd1, []int{3}
}

func (m *AddTypeReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddTypeReq.Unmarshal(m, b)
}
func (m *AddTypeReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddTypeReq.Marshal(b, m, deterministic)
}
func (m *AddTypeReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddTypeReq.Merge(m, src)
}
func (m *AddTypeReq) XXX_Size() int {
	return xxx_messageInfo_AddTypeReq.Size(m)
}
func (m *AddTypeReq) XXX_DiscardUnknown() {
	xxx_messageInfo_AddTypeReq.DiscardUnknown(m)
}

var xxx_messageInfo_AddTypeReq proto.InternalMessageInfo

func (m *AddTypeReq) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type TypesResp struct {
	Items                []*TypeResp `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	Total                uint32      `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *TypesResp) Reset()         { *m = TypesResp{} }
func (m *TypesResp) String() string { return proto.CompactTextString(m) }
func (*TypesResp) ProtoMessage()    {}
func (*TypesResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_e114ad14deab1dd1, []int{4}
}

func (m *TypesResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TypesResp.Unmarshal(m, b)
}
func (m *TypesResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TypesResp.Marshal(b, m, deterministic)
}
func (m *TypesResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TypesResp.Merge(m, src)
}
func (m *TypesResp) XXX_Size() int {
	return xxx_messageInfo_TypesResp.Size(m)
}
func (m *TypesResp) XXX_DiscardUnknown() {
	xxx_messageInfo_TypesResp.DiscardUnknown(m)
}

var xxx_messageInfo_TypesResp proto.InternalMessageInfo

func (m *TypesResp) GetItems() []*TypeResp {
	if m != nil {
		return m.Items
	}
	return nil
}

func (m *TypesResp) GetTotal() uint32 {
	if m != nil {
		return m.Total
	}
	return 0
}

type FndTypesReq struct {
	Limit                uint32   `protobuf:"varint,1,opt,name=limit,proto3" json:"limit,omitempty"`
	Lapse                uint32   `protobuf:"varint,2,opt,name=lapse,proto3" json:"lapse,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FndTypesReq) Reset()         { *m = FndTypesReq{} }
func (m *FndTypesReq) String() string { return proto.CompactTextString(m) }
func (*FndTypesReq) ProtoMessage()    {}
func (*FndTypesReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_e114ad14deab1dd1, []int{5}
}

func (m *FndTypesReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FndTypesReq.Unmarshal(m, b)
}
func (m *FndTypesReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FndTypesReq.Marshal(b, m, deterministic)
}
func (m *FndTypesReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FndTypesReq.Merge(m, src)
}
func (m *FndTypesReq) XXX_Size() int {
	return xxx_messageInfo_FndTypesReq.Size(m)
}
func (m *FndTypesReq) XXX_DiscardUnknown() {
	xxx_messageInfo_FndTypesReq.DiscardUnknown(m)
}

var xxx_messageInfo_FndTypesReq proto.InternalMessageInfo

func (m *FndTypesReq) GetLimit() uint32 {
	if m != nil {
		return m.Limit
	}
	return 0
}

func (m *FndTypesReq) GetLapse() uint32 {
	if m != nil {
		return m.Lapse
	}
	return 0
}

type PostResp struct {
	Id                   string               `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Slug                 string               `protobuf:"bytes,2,opt,name=slug,proto3" json:"slug,omitempty"`
	Title                string               `protobuf:"bytes,3,opt,name=title,proto3" json:"title,omitempty"`
	Body                 string               `protobuf:"bytes,4,opt,name=body,proto3" json:"body,omitempty"`
	TypeId               string               `protobuf:"bytes,5,opt,name=typeId,proto3" json:"typeId,omitempty"`
	Created              *timestamp.Timestamp `protobuf:"bytes,6,opt,name=created,proto3" json:"created,omitempty"`
	Updated              *timestamp.Timestamp `protobuf:"bytes,7,opt,name=updated,proto3" json:"updated,omitempty"`
	Deleted              *timestamp.Timestamp `protobuf:"bytes,8,opt,name=deleted,proto3" json:"deleted,omitempty"`
	Blocked              *timestamp.Timestamp `protobuf:"bytes,9,opt,name=blocked,proto3" json:"blocked,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *PostResp) Reset()         { *m = PostResp{} }
func (m *PostResp) String() string { return proto.CompactTextString(m) }
func (*PostResp) ProtoMessage()    {}
func (*PostResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_e114ad14deab1dd1, []int{6}
}

func (m *PostResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PostResp.Unmarshal(m, b)
}
func (m *PostResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PostResp.Marshal(b, m, deterministic)
}
func (m *PostResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PostResp.Merge(m, src)
}
func (m *PostResp) XXX_Size() int {
	return xxx_messageInfo_PostResp.Size(m)
}
func (m *PostResp) XXX_DiscardUnknown() {
	xxx_messageInfo_PostResp.DiscardUnknown(m)
}

var xxx_messageInfo_PostResp proto.InternalMessageInfo

func (m *PostResp) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *PostResp) GetSlug() string {
	if m != nil {
		return m.Slug
	}
	return ""
}

func (m *PostResp) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *PostResp) GetBody() string {
	if m != nil {
		return m.Body
	}
	return ""
}

func (m *PostResp) GetTypeId() string {
	if m != nil {
		return m.TypeId
	}
	return ""
}

func (m *PostResp) GetCreated() *timestamp.Timestamp {
	if m != nil {
		return m.Created
	}
	return nil
}

func (m *PostResp) GetUpdated() *timestamp.Timestamp {
	if m != nil {
		return m.Updated
	}
	return nil
}

func (m *PostResp) GetDeleted() *timestamp.Timestamp {
	if m != nil {
		return m.Deleted
	}
	return nil
}

func (m *PostResp) GetBlocked() *timestamp.Timestamp {
	if m != nil {
		return m.Blocked
	}
	return nil
}

type AddPostReq struct {
	Title                string   `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
	Body                 string   `protobuf:"bytes,2,opt,name=body,proto3" json:"body,omitempty"`
	TypeId               string   `protobuf:"bytes,3,opt,name=typeId,proto3" json:"typeId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AddPostReq) Reset()         { *m = AddPostReq{} }
func (m *AddPostReq) String() string { return proto.CompactTextString(m) }
func (*AddPostReq) ProtoMessage()    {}
func (*AddPostReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_e114ad14deab1dd1, []int{7}
}

func (m *AddPostReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddPostReq.Unmarshal(m, b)
}
func (m *AddPostReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddPostReq.Marshal(b, m, deterministic)
}
func (m *AddPostReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddPostReq.Merge(m, src)
}
func (m *AddPostReq) XXX_Size() int {
	return xxx_messageInfo_AddPostReq.Size(m)
}
func (m *AddPostReq) XXX_DiscardUnknown() {
	xxx_messageInfo_AddPostReq.DiscardUnknown(m)
}

var xxx_messageInfo_AddPostReq proto.InternalMessageInfo

func (m *AddPostReq) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *AddPostReq) GetBody() string {
	if m != nil {
		return m.Body
	}
	return ""
}

func (m *AddPostReq) GetTypeId() string {
	if m != nil {
		return m.TypeId
	}
	return ""
}

type OvrPostReq struct {
	Id                   string      `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Req                  *AddPostReq `protobuf:"bytes,2,opt,name=req,proto3" json:"req,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *OvrPostReq) Reset()         { *m = OvrPostReq{} }
func (m *OvrPostReq) String() string { return proto.CompactTextString(m) }
func (*OvrPostReq) ProtoMessage()    {}
func (*OvrPostReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_e114ad14deab1dd1, []int{8}
}

func (m *OvrPostReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_OvrPostReq.Unmarshal(m, b)
}
func (m *OvrPostReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_OvrPostReq.Marshal(b, m, deterministic)
}
func (m *OvrPostReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OvrPostReq.Merge(m, src)
}
func (m *OvrPostReq) XXX_Size() int {
	return xxx_messageInfo_OvrPostReq.Size(m)
}
func (m *OvrPostReq) XXX_DiscardUnknown() {
	xxx_messageInfo_OvrPostReq.DiscardUnknown(m)
}

var xxx_messageInfo_OvrPostReq proto.InternalMessageInfo

func (m *OvrPostReq) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *OvrPostReq) GetReq() *AddPostReq {
	if m != nil {
		return m.Req
	}
	return nil
}

type PostsResp struct {
	Posts                []*PostResp `protobuf:"bytes,1,rep,name=posts,proto3" json:"posts,omitempty"`
	Total                uint32      `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *PostsResp) Reset()         { *m = PostsResp{} }
func (m *PostsResp) String() string { return proto.CompactTextString(m) }
func (*PostsResp) ProtoMessage()    {}
func (*PostsResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_e114ad14deab1dd1, []int{9}
}

func (m *PostsResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PostsResp.Unmarshal(m, b)
}
func (m *PostsResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PostsResp.Marshal(b, m, deterministic)
}
func (m *PostsResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PostsResp.Merge(m, src)
}
func (m *PostsResp) XXX_Size() int {
	return xxx_messageInfo_PostsResp.Size(m)
}
func (m *PostsResp) XXX_DiscardUnknown() {
	xxx_messageInfo_PostsResp.DiscardUnknown(m)
}

var xxx_messageInfo_PostsResp proto.InternalMessageInfo

func (m *PostsResp) GetPosts() []*PostResp {
	if m != nil {
		return m.Posts
	}
	return nil
}

func (m *PostsResp) GetTotal() uint32 {
	if m != nil {
		return m.Total
	}
	return 0
}

type FndPostsReq struct {
	Keywords             []string             `protobuf:"bytes,1,rep,name=keywords,proto3" json:"keywords,omitempty"`
	Created              *timestamp.Timestamp `protobuf:"bytes,2,opt,name=created,proto3" json:"created,omitempty"`
	Updated              *timestamp.Timestamp `protobuf:"bytes,3,opt,name=updated,proto3" json:"updated,omitempty"`
	Deleted              *timestamp.Timestamp `protobuf:"bytes,4,opt,name=deleted,proto3" json:"deleted,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *FndPostsReq) Reset()         { *m = FndPostsReq{} }
func (m *FndPostsReq) String() string { return proto.CompactTextString(m) }
func (*FndPostsReq) ProtoMessage()    {}
func (*FndPostsReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_e114ad14deab1dd1, []int{10}
}

func (m *FndPostsReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FndPostsReq.Unmarshal(m, b)
}
func (m *FndPostsReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FndPostsReq.Marshal(b, m, deterministic)
}
func (m *FndPostsReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FndPostsReq.Merge(m, src)
}
func (m *FndPostsReq) XXX_Size() int {
	return xxx_messageInfo_FndPostsReq.Size(m)
}
func (m *FndPostsReq) XXX_DiscardUnknown() {
	xxx_messageInfo_FndPostsReq.DiscardUnknown(m)
}

var xxx_messageInfo_FndPostsReq proto.InternalMessageInfo

func (m *FndPostsReq) GetKeywords() []string {
	if m != nil {
		return m.Keywords
	}
	return nil
}

func (m *FndPostsReq) GetCreated() *timestamp.Timestamp {
	if m != nil {
		return m.Created
	}
	return nil
}

func (m *FndPostsReq) GetUpdated() *timestamp.Timestamp {
	if m != nil {
		return m.Updated
	}
	return nil
}

func (m *FndPostsReq) GetDeleted() *timestamp.Timestamp {
	if m != nil {
		return m.Deleted
	}
	return nil
}

type RmvPostReq struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RmvPostReq) Reset()         { *m = RmvPostReq{} }
func (m *RmvPostReq) String() string { return proto.CompactTextString(m) }
func (*RmvPostReq) ProtoMessage()    {}
func (*RmvPostReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_e114ad14deab1dd1, []int{11}
}

func (m *RmvPostReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RmvPostReq.Unmarshal(m, b)
}
func (m *RmvPostReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RmvPostReq.Marshal(b, m, deterministic)
}
func (m *RmvPostReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RmvPostReq.Merge(m, src)
}
func (m *RmvPostReq) XXX_Size() int {
	return xxx_messageInfo_RmvPostReq.Size(m)
}
func (m *RmvPostReq) XXX_DiscardUnknown() {
	xxx_messageInfo_RmvPostReq.DiscardUnknown(m)
}

var xxx_messageInfo_RmvPostReq proto.InternalMessageInfo

func (m *RmvPostReq) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type RmvPostResp struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RmvPostResp) Reset()         { *m = RmvPostResp{} }
func (m *RmvPostResp) String() string { return proto.CompactTextString(m) }
func (*RmvPostResp) ProtoMessage()    {}
func (*RmvPostResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_e114ad14deab1dd1, []int{12}
}

func (m *RmvPostResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RmvPostResp.Unmarshal(m, b)
}
func (m *RmvPostResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RmvPostResp.Marshal(b, m, deterministic)
}
func (m *RmvPostResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RmvPostResp.Merge(m, src)
}
func (m *RmvPostResp) XXX_Size() int {
	return xxx_messageInfo_RmvPostResp.Size(m)
}
func (m *RmvPostResp) XXX_DiscardUnknown() {
	xxx_messageInfo_RmvPostResp.DiscardUnknown(m)
}

var xxx_messageInfo_RmvPostResp proto.InternalMessageInfo

func init() {
	proto.RegisterType((*CommentResp)(nil), "pb.CommentResp")
	proto.RegisterType((*AddCommentResp)(nil), "pb.AddCommentResp")
	proto.RegisterType((*TypeResp)(nil), "pb.TypeResp")
	proto.RegisterType((*AddTypeReq)(nil), "pb.AddTypeReq")
	proto.RegisterType((*TypesResp)(nil), "pb.TypesResp")
	proto.RegisterType((*FndTypesReq)(nil), "pb.FndTypesReq")
	proto.RegisterType((*PostResp)(nil), "pb.PostResp")
	proto.RegisterType((*AddPostReq)(nil), "pb.AddPostReq")
	proto.RegisterType((*OvrPostReq)(nil), "pb.OvrPostReq")
	proto.RegisterType((*PostsResp)(nil), "pb.PostsResp")
	proto.RegisterType((*FndPostsReq)(nil), "pb.FndPostsReq")
	proto.RegisterType((*RmvPostReq)(nil), "pb.RmvPostReq")
	proto.RegisterType((*RmvPostResp)(nil), "pb.RmvPostResp")
}

func init() { proto.RegisterFile("post.proto", fileDescriptor_e114ad14deab1dd1) }

var fileDescriptor_e114ad14deab1dd1 = []byte{
	// 605 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x54, 0xcd, 0x6a, 0xdb, 0x40,
	0x10, 0x46, 0xf2, 0x9f, 0x3c, 0x8e, 0x9d, 0xb0, 0xb4, 0x45, 0x88, 0x40, 0xcd, 0x9e, 0x42, 0x0e,
	0x32, 0xb8, 0xbd, 0x24, 0x87, 0x40, 0x28, 0x2d, 0xf4, 0xd2, 0x16, 0x91, 0x17, 0x90, 0xb2, 0xdb,
	0x20, 0x22, 0x69, 0xd7, 0xde, 0x4d, 0x8a, 0x29, 0xbd, 0xf4, 0x15, 0xfa, 0x52, 0x85, 0x1e, 0xfb,
	0x0a, 0x7d, 0x84, 0x3e, 0x40, 0xd9, 0xd9, 0x5d, 0x59, 0x0e, 0x09, 0x29, 0xb9, 0xed, 0xcc, 0x7c,
	0xdf, 0x7c, 0xd6, 0x7c, 0x33, 0x06, 0x90, 0x42, 0xe9, 0x54, 0xae, 0x85, 0x16, 0x24, 0x94, 0x45,
	0x72, 0x78, 0x25, 0xc4, 0x55, 0xc5, 0x17, 0xb9, 0x2c, 0x17, 0x79, 0xd3, 0x08, 0x9d, 0xeb, 0x52,
	0x34, 0xca, 0x22, 0x92, 0x97, 0xae, 0x8a, 0x51, 0x71, 0xf3, 0x79, 0xa1, 0xcb, 0x9a, 0x2b, 0x9d,
	0xd7, 0xd2, 0x02, 0xe8, 0x14, 0x26, 0x6f, 0x44, 0x5d, 0xf3, 0x46, 0x67, 0x5c, 0x49, 0x7a, 0x00,
	0xb3, 0x73, 0xc6, 0xba, 0x99, 0x14, 0xa2, 0x8b, 0x8d, 0xe4, 0xe6, 0x4d, 0x66, 0x10, 0x96, 0x2c,
	0x0e, 0xe6, 0xc1, 0xd1, 0x38, 0x0b, 0x4b, 0x46, 0x08, 0xf4, 0x9b, 0xbc, 0xe6, 0x71, 0x88, 0x19,
	0x7c, 0xd3, 0x39, 0xc0, 0x39, 0x63, 0x96, 0xb2, 0x6a, 0x11, 0x41, 0x07, 0xf1, 0x16, 0xc6, 0xa6,
	0xac, 0xb0, 0x25, 0x85, 0x41, 0xa9, 0x79, 0xad, 0xe2, 0x60, 0xde, 0x3b, 0x9a, 0x2c, 0xf7, 0x52,
	0x59, 0xa4, 0x5e, 0x2f, 0xb3, 0x25, 0xf2, 0x0c, 0x06, 0x5a, 0xe8, 0xbc, 0x42, 0x9d, 0x69, 0x66,
	0x03, 0x7a, 0x02, 0x93, 0x77, 0x0d, 0x73, 0x9d, 0x56, 0x06, 0x54, 0x95, 0x75, 0xa9, 0x51, 0x6a,
	0x9a, 0xd9, 0x00, 0xb3, 0xb9, 0x54, 0xdc, 0x53, 0x31, 0xa0, 0x3f, 0x43, 0x88, 0x3e, 0x09, 0xa5,
	0x1f, 0xfa, 0x28, 0x55, 0xdd, 0x5c, 0xf9, 0x8f, 0x32, 0x6f, 0xfc, 0x05, 0xa5, 0xae, 0x78, 0xdc,
	0xc3, 0xa4, 0x0d, 0x0c, 0xb2, 0x10, 0x6c, 0x13, 0xf7, 0x2d, 0xd2, 0xbc, 0xc9, 0x0b, 0x18, 0xea,
	0x8d, 0xe4, 0xef, 0x59, 0x3c, 0xc0, 0xac, 0x8b, 0xc8, 0x6b, 0x18, 0x5d, 0xae, 0x79, 0xae, 0x39,
	0x8b, 0x87, 0xf3, 0xe0, 0x68, 0xb2, 0x4c, 0x52, 0x6b, 0x4d, 0xea, 0xad, 0x49, 0x2f, 0xbc, 0x35,
	0x99, 0x87, 0x1a, 0xd6, 0x8d, 0x64, 0xc8, 0x1a, 0x3d, 0xce, 0x72, 0x50, 0xc3, 0x62, 0xbc, 0xe2,
	0x86, 0x15, 0x3d, 0xce, 0x72, 0x50, 0xc3, 0x2a, 0x2a, 0x71, 0x79, 0xcd, 0x59, 0x3c, 0x7e, 0x9c,
	0xe5, 0xa0, 0xf4, 0x03, 0xda, 0x6d, 0x87, 0xb9, 0xda, 0xce, 0x29, 0xb8, 0x6f, 0x4e, 0xe1, 0xbd,
	0x73, 0xea, 0x75, 0xe7, 0x44, 0xcf, 0x00, 0x3e, 0xde, 0xae, 0x7d, 0xbf, 0xbb, 0xde, 0xcc, 0xa1,
	0xb7, 0xe6, 0x2b, 0x6c, 0x34, 0x59, 0xce, 0xcc, 0xae, 0x6c, 0xc5, 0x33, 0x53, 0x32, 0xcb, 0x65,
	0xe2, 0x76, 0xb9, 0xcc, 0xb5, 0xec, 0x2c, 0x97, 0xf7, 0x3d, 0xb3, 0xa5, 0x07, 0x96, 0xeb, 0x57,
	0x80, 0xdb, 0xe5, 0x5a, 0xad, 0x48, 0x02, 0xd1, 0x35, 0xdf, 0x7c, 0x11, 0x6b, 0x66, 0x9b, 0x8d,
	0xb3, 0x36, 0xee, 0x5a, 0x1b, 0x3e, 0xc9, 0xda, 0xde, 0x93, 0xac, 0xed, 0xff, 0xb7, 0xb5, 0xf4,
	0x10, 0x20, 0xab, 0x6f, 0x1f, 0x18, 0xaa, 0xf9, 0x0b, 0x68, 0xab, 0x4a, 0x2e, 0xff, 0x86, 0xd0,
	0x37, 0x01, 0x39, 0x81, 0x91, 0xbb, 0x64, 0xe2, 0x47, 0xed, 0xce, 0x3a, 0xd9, 0x39, 0x53, 0x7a,
	0xf0, 0xfd, 0xf7, 0x9f, 0x1f, 0x21, 0xd0, 0xc1, 0xc2, 0x98, 0x78, 0x1a, 0x1c, 0x93, 0x53, 0x88,
	0xfc, 0x6d, 0x92, 0x7d, 0x83, 0xed, 0x5c, 0x6a, 0x32, 0xf5, 0x64, 0x34, 0x89, 0xce, 0x90, 0x1d,
	0x91, 0x21, 0xb2, 0x95, 0x93, 0xc5, 0x5f, 0x70, 0xc7, 0xe1, 0x64, 0xc7, 0xc0, 0x8e, 0xac, 0x71,
	0x72, 0x2b, 0x8b, 0xa6, 0xb5, 0xb2, 0xde, 0x42, 0x2b, 0xdb, 0xee, 0x46, 0x47, 0xd6, 0xee, 0xc1,
	0x19, 0x8c, 0xdc, 0xe2, 0x59, 0xd9, 0xed, 0x16, 0xde, 0x91, 0x7d, 0x8e, 0xc4, 0xfd, 0x04, 0x90,
	0xb8, 0xf8, 0x5a, 0xb2, 0x6f, 0x46, 0xfb, 0x0c, 0x46, 0x6e, 0x8a, 0x96, 0xbf, 0x1d, 0x78, 0xb2,
	0xbf, 0x13, 0x2b, 0x49, 0x09, 0xb6, 0xd8, 0x3b, 0xee, 0xb4, 0x28, 0x86, 0x68, 0xe0, 0xab, 0x7f,
	0x01, 0x00, 0x00, 0xff, 0xff, 0xd5, 0xd2, 0xc3, 0xfb, 0xe0, 0x05, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// PostClient is the client API for Post service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type PostClient interface {
	AddType(ctx context.Context, in *AddTypeReq, opts ...grpc.CallOption) (*TypeResp, error)
	FndTypes(ctx context.Context, in *FndTypesReq, opts ...grpc.CallOption) (*TypesResp, error)
	AddPost(ctx context.Context, in *AddPostReq, opts ...grpc.CallOption) (*PostResp, error)
	FndPosts(ctx context.Context, in *FndPostsReq, opts ...grpc.CallOption) (*PostsResp, error)
	OvrPost(ctx context.Context, in *OvrPostReq, opts ...grpc.CallOption) (*PostResp, error)
	RmvPost(ctx context.Context, in *RmvPostReq, opts ...grpc.CallOption) (*RmvPostResp, error)
}

type postClient struct {
	cc *grpc.ClientConn
}

func NewPostClient(cc *grpc.ClientConn) PostClient {
	return &postClient{cc}
}

func (c *postClient) AddType(ctx context.Context, in *AddTypeReq, opts ...grpc.CallOption) (*TypeResp, error) {
	out := new(TypeResp)
	err := c.cc.Invoke(ctx, "/pb.Post/AddType", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *postClient) FndTypes(ctx context.Context, in *FndTypesReq, opts ...grpc.CallOption) (*TypesResp, error) {
	out := new(TypesResp)
	err := c.cc.Invoke(ctx, "/pb.Post/FndTypes", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *postClient) AddPost(ctx context.Context, in *AddPostReq, opts ...grpc.CallOption) (*PostResp, error) {
	out := new(PostResp)
	err := c.cc.Invoke(ctx, "/pb.Post/AddPost", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *postClient) FndPosts(ctx context.Context, in *FndPostsReq, opts ...grpc.CallOption) (*PostsResp, error) {
	out := new(PostsResp)
	err := c.cc.Invoke(ctx, "/pb.Post/FndPosts", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *postClient) OvrPost(ctx context.Context, in *OvrPostReq, opts ...grpc.CallOption) (*PostResp, error) {
	out := new(PostResp)
	err := c.cc.Invoke(ctx, "/pb.Post/OvrPost", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *postClient) RmvPost(ctx context.Context, in *RmvPostReq, opts ...grpc.CallOption) (*RmvPostResp, error) {
	out := new(RmvPostResp)
	err := c.cc.Invoke(ctx, "/pb.Post/RmvPost", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PostServer is the server API for Post service.
type PostServer interface {
	AddType(context.Context, *AddTypeReq) (*TypeResp, error)
	FndTypes(context.Context, *FndTypesReq) (*TypesResp, error)
	AddPost(context.Context, *AddPostReq) (*PostResp, error)
	FndPosts(context.Context, *FndPostsReq) (*PostsResp, error)
	OvrPost(context.Context, *OvrPostReq) (*PostResp, error)
	RmvPost(context.Context, *RmvPostReq) (*RmvPostResp, error)
}

func RegisterPostServer(s *grpc.Server, srv PostServer) {
	s.RegisterService(&_Post_serviceDesc, srv)
}

func _Post_AddType_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddTypeReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PostServer).AddType(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.Post/AddType",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PostServer).AddType(ctx, req.(*AddTypeReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Post_FndTypes_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FndTypesReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PostServer).FndTypes(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.Post/FndTypes",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PostServer).FndTypes(ctx, req.(*FndTypesReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Post_AddPost_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddPostReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PostServer).AddPost(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.Post/AddPost",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PostServer).AddPost(ctx, req.(*AddPostReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Post_FndPosts_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FndPostsReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PostServer).FndPosts(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.Post/FndPosts",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PostServer).FndPosts(ctx, req.(*FndPostsReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Post_OvrPost_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(OvrPostReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PostServer).OvrPost(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.Post/OvrPost",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PostServer).OvrPost(ctx, req.(*OvrPostReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Post_RmvPost_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RmvPostReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PostServer).RmvPost(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.Post/RmvPost",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PostServer).RmvPost(ctx, req.(*RmvPostReq))
	}
	return interceptor(ctx, in, info, handler)
}

var _Post_serviceDesc = grpc.ServiceDesc{
	ServiceName: "pb.Post",
	HandlerType: (*PostServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "AddType",
			Handler:    _Post_AddType_Handler,
		},
		{
			MethodName: "FndTypes",
			Handler:    _Post_FndTypes_Handler,
		},
		{
			MethodName: "AddPost",
			Handler:    _Post_AddPost_Handler,
		},
		{
			MethodName: "FndPosts",
			Handler:    _Post_FndPosts_Handler,
		},
		{
			MethodName: "OvrPost",
			Handler:    _Post_OvrPost_Handler,
		},
		{
			MethodName: "RmvPost",
			Handler:    _Post_RmvPost_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "post.proto",
}
