#!/usr/bin/env bash

function main() {
    local rootDir="$(dirname "${0}")"
    local fpb2elm="$(find "${rootDir}" -name pb2elm -print -quit)"

    [[ ! -f "${fpb2elm}" || ! -x "${fpb2elm}" ]] && echo "cannot find pb2elm" >&2 && exit 1

    "${fpb2elm}" "${rootDir}/src" -I "${rootDir}/../msgs" "${rootDir}/../msgs/proto/*.proto"
}

main
