-- +migrate Up

CREATE TABLE user (
    user_id VARCHAR(26) NOT NULL PRIMARY KEY,
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    deleted_at DATETIME DEFAULT NULL,

    username VARCHAR(255) NOT NULL UNIQUE,
    email VARCHAR(255) NOT NULL UNIQUE,
    email_hold BOOL NOT NULL DEFAULT TRUE,
    altmail VARCHAR(255) NOT NULL UNIQUE,
    altmail_hold BOOL NOT NULL DEFAULT TRUE,
    full_name VARCHAR(255) NOT NULL,
    avatar VARCHAR(255) NOT NULL DEFAULT "",
    password VARCHAR(255) NOT NULL,

    last_login DATETIME DEFAULT NULL,
    blocked_at DATETIME DEFAULT NULL
);

-- +migrate Down

DROP TABLE IF EXISTS user;
